### PR TITLE
Default inputType to 'text' if type attribute not specified in input el

### PR DESCRIPTION
**Pull request by jasonsack**
I encountered this when writing simple html fixtures for a test on a project I'm working on, and lazily left out the `type` attribute for some text inputs. This causes an error in the `inputVal` method in which `inputType` is never set, and the inputType switch is never assessed.

Obviously always add the type! Since the default type is text if the attribute is not specified, it might be worth adding a default to "text" here.

### CODE REVIEW

**Comment by iamchrismiller** [comment]
Looks good. :+1: If you add a test I will merge it in otherwise it will be a couple of days before I can get to this.

**Comment by jasonsack** [comment]
Done. I wasn't exactly sure where this fit in the spec, let me know if it makes sense somewhere other than serialization.

**Comment by iamchrismiller** [comment]
Looks good, Maybe a quick test to verify the input field type is in fact defaulted to "text"

**Comment by jasonsack** [comment]
Cool, checking the .prop() should do the trick.

**Comment by iamchrismiller** [comment]
Thank you!

**Pull request merged**
